import Head from 'next/head'
import Articles from '../components/articles.js'
import article_list from '../public/data/articles.json'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>ytomi-chan</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main className={styles.main}>
          <Articles articles={article_list}/>
        </main>

      </div>
    </>
  )
}
